# -*- coding: utf-8 -*-
"""2_Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OLGws_-mqLwRpiS9oQFtrkKOrGmPECrD
"""

# %load_ext autoreload
# %autoreload 2

import os

from main import get_data, get_model
from callbacks import get_callbacks
import config

print(config.datasets)

from argparse import Namespace

for s in [30, 45, 60, 75]:

  s_string = '%sk' %s
  # folk30k
  args = {
      "new": True,
      "id": "model_folk%s" %s_string,
      "cells": 64,
      "layers": 2,
      "bi": True,
      "att": True,
      "tqdm": True,
      "dataset": "folk%s" %s_string,
      "tqdm": True,
  }

  args = Namespace(**args)
  
  dataset = config.datasets[args.dataset]
  print('using dataset: ', dataset['path'])
  X_train, X_val, y_train, y_val = get_data(dataset)
  
  model, model_dir = get_model(args, dataset['shape'])
  verbosity, callbacks = get_callbacks(model_dir, args, model)

  history = model.fit(
    X_train, y_train,
    epochs=30,
    batch_size=config.BATCH_SIZE,
    callbacks=callbacks,
    validation_data=(X_val, y_val),
    verbose=verbosity
  )
